# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json
# Has already been submitted to pkgs.

PackageIdentifier: Microsoft.Azure.iisnode.Full
PackageVersion: 0.2.26
ReleaseDate: 2017-02-22
InstallerType: msi
ProductCode: '{65009631-F9DE-442B-B59B-F7BF09FD90CE}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Azure/iisnode/releases/download/v0.2.26/iisnode-full-v0.2.26-x64.msi
  InstallerSha256: C9A1ECCBE1346EBAD8EF6244E8F12F5D0AE6BD2A306335A529A6E0248BBEDAF9
  Dependencies: # According to https://github.com/Azure/iisnode/blob/master/README.md
    PackageDependencies:
    - PackageIdentifier: Microsoft.IIS.URLRewrite
    - PackageIdentifier: OpenJS.NodeJS
    WindowsFeatures:
    - IIS-WebServerManagementTools
    - IIS-ASPNET45
- Architecture: x86
  InstallerUrl: https://github.com/Azure/iisnode/releases/download/v0.2.26/iisnode-full-v0.2.26-x86.msi
  InstallerSha256: f47c330ef39be62601b739536e96ff404ed8c5c77e39f1039990d2123d259e8d
  UnsupportedOSArchitectures:
  - x64
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.IIS.URLRewrite
    - PackageIdentifier: OpenJS.NodeJS.22
    WindowsFeatures:
    - IIS-WebServerManagementTools
    - IIS-ASPNET45
ManifestType: installer
ManifestVersion: 1.28.0
