# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OnionUI.CHDMAN
PackageVersion: "4.3"
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: chdman\chdman.exe
  PortableCommandAlias: cue2chd
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/anzz1/DotUI-X/files/11522389/chdman.zip
  InstallerSha256: E5ECC603C36394CDF549AC9FF9276FA2A754B69A2286B3425B7C01F0EEE38742
ManifestType: installer
ManifestVersion: 1.12.0
