# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json
PackageIdentifier: Unident.Onepix.Server
PackageVersion: 2.5.5.2552
PackageLocale: en-US
Publisher: Unident AB
PackageName: Onepix Server
PackageUrl: https://onepix.app/en/download
License: Proprietary
Copyright: © 2023 Unident AB
ShortDescription: A professional image management software for dental practices designed by Unident. It is an open and integrated system that can be used with almost all radiography hardware and many journal systems in the market.
Moniker: onepixserver
Tags:
- onepix-server
- dental-clinics
- dentalclinics
- dental-offices
- dentaloffices
- dentists
- radiography-hardware
- radiographyhardware
- intraoral-sensors
- extraoral-sensors
- 1pix
- requires-database-connection
ReleaseNotesUrl: https://onepix.app/en/news
ManifestType: defaultLocale
ManifestVersion: 1.28.0