# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Unident.Onepix.Server
PackageVersion: 2.5.5.2552
ReleaseDate: 2023-12-08
InstallerType: exe
InstallerSwitches:
  Silent: /exenoui /quiet /qn /norestart
  SilentWithProgress: /exenoui /quiet /qn /norestart
Installers:
- Architecture: x86
  InstallerUrl: https://onepix-site.s3.eu-north-1.amazonaws.com/ONEPIX/SETUP/OnepixServer_2.5.5.2552.exe
  InstallerSha256: B6FF7D3DC75C8AC6EEBDC568C3D06F6A7EA50A228950BB69F25D7874542CC18F
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2008.x86
  - PackageIdentifier: Microsoft.VCRedist.2010.x86
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
  # - PackageIdentifier: Microsoft.SQLServer.2022.Express (Depends on https://github.com/microsoft/winget-pkgs/issues/378926; it is not a hard dependency, but would be convenient)
  # - PackageIdentifier: Microsoft.MSXML.4 (Depends on https://github.com/microsoft/winget-pkgs/pull/378943; hard dependency)
ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.28.0
