# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Roland.BossToneStudio.GT-1
PackageVersion: 1.0.2
ReleaseDate: 2018-03-01
InstallerType: zip
NestedInstallerType: exe # Adobe AIR-type installer
InstallerSwitches:
  Silent: -silent -eulaAccepted
  SilentWithProgress: -silent -eulaAccepted
ElevationRequirement: elevationRequired
NestedInstallerFiles:
- RelativeFilePath: bts_gt1_w102\BOSS_TONE_STUDIO_for_GT1.exe
Installers:
- Architecture: x86
  InstallerUrl: https://static.roland.com/assets/media/zip/bts_gt1_w102.zip
  InstallerSha256: 162B25D1072239CEC6917FEAA185BD6917DB0DF6AD301126C92A211F5F0F0293
Dependencies:
  PackageDependencies:
  - PackageIdentifier: HARMAN.AdobeAIR
ManifestType: installer
ManifestVersion: 1.12.0