#yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KeepSolid.VPNUnlimited
PackageVersion: 9.5.1
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://geo.keepsolidcdn.com/soft/vpn/Win/VPN_Unlimited_v9.5.1.exe
  InstallerSha256: fd5169997d87a7a8078c41d4d0140cde73a0b211145512b2aa6b3458d4067c67
ManifestType: installer
ManifestVersion: 1.12.0