# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.28.0.schema.json
PackageIdentifier: Microsoft.SystemCenter.ServiceManager.Console
PackageVersion: 10.25.1523
PackageLocale: nb-NO
PackageName: System Center Service Manager-konsoll
License: Proprietær
ShortDescription: Kontrollpanel for System Center Service Manager.
Tags:
- system-center-service-manager-konsoll
- systemcenterservicemanagerkonsoll
- scsmc
ManifestType: locale
ManifestVersion: 1.28.0
