# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Is not in extras due to: The .exe-s were deemed insignificant, as the app's primary focus was development .dll-s; https://github.com/pl4nty/winget-extras/pull/889

PackageIdentifier: KhronosGroup.OpenXRLoader
PackageVersion: 1.1.61
ReleaseDate: 2026-07-06
InstallerType: zip
NestedInstallerType: portable
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: Win32\bin\hello_xr.exe
  - RelativeFilePath: Win32\bin\openxr_runtime_list.exe
  - RelativeFilePath: Win32\bin\openxr_runtime_list_json.exe
  InstallerUrl: https://github.com/KhronosGroup/OpenXR-SDK-Source/releases/download/release-1.1.61/openxr_loader_windows-1.1.61.zip
  InstallerSha256: CFDCA34B8CB4C2BEF6DEA05273DAFF987E58C97D5767C04F0A20B1029EAABE7F
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: x64\bin\hello_xr.exe
  - RelativeFilePath: x64\bin\openxr_runtime_list.exe
  - RelativeFilePath: x64\bin\openxr_runtime_list_json.exe
  InstallerUrl: https://github.com/KhronosGroup/OpenXR-SDK-Source/releases/download/release-1.1.61/openxr_loader_windows-1.1.61.zip
  InstallerSha256: CFDCA34B8CB4C2BEF6DEA05273DAFF987E58C97D5767C04F0A20B1029EAABE7F
- Architecture: ARM64
  NestedInstallerFiles:
  - RelativeFilePath: ARM64_uwp\bin\hello_xr.exe
  - RelativeFilePath: ARM64_uwp\bin\openxr_runtime_list.exe
  - RelativeFilePath: ARM64_uwp\bin\openxr_runtime_list_json.exe
  InstallerUrl: https://github.com/KhronosGroup/OpenXR-SDK-Source/releases/download/release-1.1.61/openxr_loader_windows-1.1.61.zip
  InstallerSha256: CFDCA34B8CB4C2BEF6DEA05273DAFF987E58C97D5767C04F0A20B1029EAABE7F
ManifestType: installer
ManifestVersion: 1.12.0
