# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: KhronosGroup.OpenXRLoader
PackageVersion: 1.1.61
PackageLocale: en
Publisher: Khronos Group
PackageName: OpenXR Loader
PackageUrl: https://github.com/KhronosGroup/OpenXR-SDK-Source
License: Apache-2.0
ShortDescription: grebuniagbrteuiaogbeoaiguetrbagosr
Moniker: openxrloader
Tags:
- openxr-loader
- open-xr-loader
- openxr-sdk-source
- openxrsdksource
- requirescmd
ManifestType: defaultLocale
ManifestVersion: 1.12.0