#yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Xelitan.HashCalculator
PackageVersion: "1.2"
ReleaseDate: 2023-09-09
InstallerType: inno
Installers:
- Architecture: x86
  InstallerUrl: https://xelitan.com/download/xelitan_hash_v12.exe
  InstallerSha256: 1AB02E32380F81F83C9414A7416CCB4F80A184C9F55140A54C57FDD7613F87C3
ManifestType: installer
ManifestVersion: 1.12.0