# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json
# Has not yet been submitted to pkgs due to: I've got cold feet about this manifest due to how its hourly PowerShell launches causes the mouse cursor to defocus from anything else the user is doing.

PackageIdentifier: shoebbhaikhan.Upkeep
PackageVersion: "1"
ReleaseDate: 2026-04-02
Platform:
- Windows.Desktop
InstallerType: portable
Commands:
- upkeep
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/shoebbhaikhan/Upkeep/releases/download/v1.0.0/Upkeep.exe
  InstallerSha256: 1D4AB50108E08533BC3A51868B54D3D8BA117CDDB5EE71EB600E9522C9FD6A7D
ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.28.0
