# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: irzyxa.Volume2
PackageVersion: 1.1.9.470
PackageLocale: en-US
Publisher: irzyxa
PackageName: Volume2
License: Custom; circa equivalent to CC SA-ND
ShortDescription: Advanced Windows volume control.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
