# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Microsoft.CsWinRT
PackageVersion: 2.2.0
PackageLocale: en-GB
PackageName: CsWinRT
ShortDescription: Provides Windows Runtime (WinRT) projection support for the C# language.
Tags:
- Microsoft.Windows.CsWinRT
- microsoft-cswinrt
- microsoftcswinrtiidoptimiser
- iid-optimiser
- iidoptimiser
- csharp
- c#
- requirescmd
ManifestType: locale
ManifestVersion: 1.12.0
