# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json
PackageIdentifier: Python.PythonEmbeddablePackage.3.14
PackageVersion: 3.14.5
ReleaseDate: 2026-05-10
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: python.exe
- RelativeFilePath: pythonw.exe
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://www.python.org/ftp/python/3.14.5/python-3.14.5-embed-amd64.zip
  InstallerSha256: BA6BD811C4EEDB19195CF275770EF127E893D63701E24152606E2CB76F6D876A
  AppsAndFeaturesEntries:
  - DisplayName: Python Embeddable Package 3.14 (x64)
- Architecture: x86
  InstallerUrl: https://www.python.org/ftp/python/3.14.5/python-3.14.5-embed-win32.zip
  InstallerSha256: 9b461868ff63d5fd4275f8f7a802812672eacc8486aba9d7c6a0c4e3290af52b
  AppsAndFeaturesEntries:
  - DisplayName: Python Embeddable Package 3.14 (x86)
- Architecture: arm64
  InstallerUrl: https://www.python.org/ftp/python/3.14.5/python-3.14.5-embed-arm64.zip
  InstallerSha256: 0c078f7646c3b13c2dce0bb690994e431ed5269788803deffb459ee9e78b684e
  AppsAndFeaturesEntries:
  - DisplayName: Python Embeddable Package 3.14 (ARM64)
ManifestType: installer
ManifestVersion: 1.28.0