# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Python.PythonEmbeddablePackage.3.14
PackageVersion: 3.14.5
PackageLocale: en-US
Publisher: Python Software Foundation
PackageName: Python Embeddable Package 3.14
PackageUrl: https://www.python.org/downloads/
License: PSF-2.0
ShortDescription: A lightweight, portable-only version of Python 3.14.
Tags:
- python-embeddable-package
- requirescmd
ManifestType: defaultLocale
ManifestVersion: 1.12.0