# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.AppInstaller.WingetPkgsSource
PackageVersion: 2026.404.2440.21
Platform:
- Windows.Universal
MinimumOSVersion: 10.0.16299.0
InstallerType: msix
PackageFamilyName: Microsoft.Winget.Source_8wekyb3d8bbwe
Installers:
- Architecture: neutral
  InstallerUrl: https://cdn.winget.microsoft.com/cache/source.msix
  InstallerSha256: 113569885D6BD61A32FB0E29127AE60470AAFA64DE3C44F29E371CB4EB0590B3
  SignatureSha256: DB4D2FF995933C553C3E5F4336C1A99844ABE850C0C5398F96383240DE13ADDE
ManifestType: installer
ManifestVersion: 1.12.0