# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Discriminator.PDW
PackageVersion: 3.2b01
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: PDW32b01.exe
  PortableCommandAlias: pdw
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  InstallerUrl: https://www.discriminator.nl/pdw/pdw3.2b01.zip
  InstallerSha256: AF64DA59BEE8C2F702432856ACA3ECFD932A3DDC968ADAED4B7924677A80B358
ManifestType: installer
ManifestVersion: 1.12.0
