# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: osmanonurkoc.WinGetInstaller
PackageVersion: 1.3.3.0
PackageLocale: en-US
Publisher: osmanonurkoc
PackageName: Software Installer
PackageUrl: https://github.com/osmanonurkoc/WinGet_Installer
License: MIT
Copyright: Osman Onur Koç
ShortDescription: A modern GUI wrapper for Winget written in PowerShell/WPF. Features bulk installation, JSON/XML configuration, dark mode, and an automated self-repair system for Winget source errors.
Tags:
- winget_installer
- winget-installer
- software-installer
- softwareinstaller
- winget-gui
- wingetgui
ManifestType: defaultLocale
ManifestVersion: 1.12.0