# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Viewizard.AstroMenace
PackageVersion: 1.4.3
PackageLocale: en
Publisher: Viewizard
PackageName: AstroMenace
License: Mostly GPLv3 except for a few assets
LicenseUrl: https://github.com/viewizard/astromenace/blob/master/LICENSE.md
ShortDescription: Hardcore 3D space scroll-shooter with spaceship upgrade possibilities.
Moniker: astromenace
Tags:
- astro-menace
- videogame
- games
- singleplayer
ManifestType: defaultLocale
ManifestVersion: 1.12.0