# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.Intune.WinAppUtil
PackageVersion: 1.8.7
ReleaseDate: 2025-08-13
InstallerType: portable
Commands:
- intunewinapputil
Installers:
- Architecture: x64
  InstallerUrl: https://raw.github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/99dbe4bed2e558e5e14722eded97a7538da015b6/IntuneWinAppUtil.exe
  InstallerSha256: C1BA45B5CB939E84AF064BB7FF4B38FB3DFE33C8DC1078FD9B157672EAE671F6
FileExtensions:
- exe
ManifestType: installer
ManifestVersion: 1.12.0