# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json
PackageIdentifier: reaConverter.reaConverterLite
PackageVersion: 8.0.228
ReleaseDate: 2026-06-19
InstallerType: inno
Installers:
- Architecture: x86
  InstallerUrl: https://www.reaconverter.com/download/reaConverterLite-Setup.exe
  InstallerSha256: 5F358DB52C58C61EE6A927B7E58A0EBDFC17B77A43452383C5B9C9696053924B
FileExtensions:
- avif
- bmp
- gif
- ico
- jpg
- jxl
- png
- tif
- webp
ManifestType: installer
ManifestVersion: 1.28.0