# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Intel.ACAT
PackageVersion: "3.13"
PackageLocale: en-US
Publisher: Intel Corporation
PackageName: Assistive Context-Aware Toolkit
PackageUrl: https://github.com/intel/acat
License: Apache-2.0
ShortDescription: Designed to enhance communication for individuals with restricted speech and typing capabilities. It achieves this by providing functionalities like keyboard simulation, word/sentence prediction, and speech synthesis.
Tags:
- intel-acat
- intelacat
- assistive-context-aware-toolkit
- assistivecontextawaretoolkit
- accessibility
- speech-impairments
- speechimpairments
ManifestType: defaultLocale
ManifestVersion: 1.12.0