# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Samsung.Odyssey3DHub
PackageVersion: 1.5.1
PackageLocale: en-US
Publisher: Samsung Electronics Co., Ltd.
PackageName: Samsung Odyssey 3D Hub
PackageUrl: https://www.samsung.com/us/support/downloads/?model=N0061851&modelCode=LS27FG900XNXZA
License: Proprietary
ShortDescription: Jump into 3D quickly and easily with Odyssey 3D Hub, which delivers the best 3D video and gaming experience you can get. Register and access supported games, and adjust settings to get the most out of 3D across your favorite content.
Moniker: odyssey3dhub
Tags:
- samsung-odyssey-3d-hub
- xp8lx6slrzb813
ManifestType: defaultLocale
ManifestVersion: 1.12.0