# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: SpiceSpace.qxl-wddm-dod
PackageVersion: "0.21"
PackageLocale: en-US
Publisher: Red Hat, Inc.
PackageName: qxl-wddm-dod
PackageUrl: https://www.spice-space.org/download.html
License: Unclear (Freeware)
ShortDescription: gtbnreuidgbtueriogbertouigbtr
Tags:
- driver
- qxldod.inf
ManifestType: defaultLocale
ManifestVersion: 1.12.0
