# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RenPy.RenPySDK.Fonts
PackageVersion: 8.3.7
InstallerType: zip
NestedInstallerType: font
Installers:
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\sdk-fonts\SourceHanSansLite.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\renpy\common\DejaVuSans-Bold.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\renpy\common\DejaVuSans.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\renpy\common\TwemojiCOLRv0.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\renpy\common\_OpenDyslexic3-Regular.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\launcher\game\fonts\Roboto-Light.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\launcher\game\fonts\Roboto-Regular.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\renpy\common\_theme_awt\Quicksand-Bold.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\renpy\common\_theme_awt\Quicksand-Regular.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\doc\_static\bootstrap-3.4.1\fonts\glyphicons-halflings-regular.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: renpy-8.3.7-sdk\doc\_static\css\fonts\fontawesome-webfont.ttf
  InstallerUrl: https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
  InstallerSha256: 7722E17AED8C174307C1E69D087D74EF009BC164A4DE4830149794F8DA3F7ECF
ManifestType: installer
ManifestVersion: 1.12.0
