# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: XnSoft.XnRetro
PackageVersion: "1.30"
DefaultLocale: en
ManifestType: version
ManifestVersion: 1.12.0
