# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Telia.Sweden.TeliaCloud
PackageVersion: 26.3.26.31483
PackageLocale: en-US
Publisher: Telia AB
License: Proprietär
Copyright: © Telia AB. All rights reserved.
ShortDescription: Save your images, videos, and files safely and securely through Telia Cloud.
Tags:
- telia-cloud
- file-storage
- filestorage
- cloud-storage
- cloudstorage
- jottacloud
ManifestType: locale
ManifestVersion: 1.12.0