# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json
PackageIdentifier: Telia.Sweden.TeliaCloud
PackageVersion: 26.3.26.31483
DefaultLocale: sv-SE
ManifestType: version
ManifestVersion: 1.28.0