# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: RabbitMQ.Server
PackageVersion: 4.3.2
PackageLocale: en
Publisher: VMware, Inc.
PackageName: RabbitMQ Server
PackageUrl: https://github.com/rabbitmq/rabbitmq-server
License: Mostly MPLv2, with some files instead as Apache-2.0
LicenseUrl: https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/refs/heads/main/LICENSE
Copyright: © 2007-2026 VMware, Inc. or its affiliates.
ShortDescription: A feature rich, multi-protocol messaging and streaming broker.
Moniker: rabbitmq
Tags:
- rabbitmq-server
- rabbitmqserver
- rabbit-mq-server
- messaging-broker
- messagingbroker
- streaming-broker
- streamingbroker
ManifestType: defaultLocale
ManifestVersion: 1.12.0