# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Broadcom.FCDrivers
PackageVersion: 14.4.900.12
ReleaseDate: 2026-06-30
InstallerType: exe # InstallMate
InstallerSwitches:
  Silent: /q2
  SilentWithProgress: /q
Installers:
- Architecture: x86
  InstallerUrl: https://docs.broadcom.com/docs-and-downloads/oem/support/elx/rt14.4.28/14.4.900.12/elxdrvr-fc-14.4.871.0-1.exe
  InstallerSha256: 4082BB4D78775A42BA010283A47F338EE1D7974FAE2B46C890D2543B78454AF6
  ProductCode: '{C223EC5B-FE00-4731-A35A-CC844B5CA79F}' # Remember to crosscheck in the 26H1 VM.
  AppsAndFeaturesEntries:
  - ProductCode: '{C223EC5B-FE00-4731-A35A-CC844B5CA79F}'
ManifestType: installer
ManifestVersion: 1.12.0