# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: OnionUI.CHDMAN
PackageVersion: "4.3"
PackageLocale: en-US
Publisher: The Onion UI Development Team and/or MAME
PackageName: CHDMAN
License: hgtrshjtydjtydyj
ShortDescription: Convert your CD roms into a lossless compressed format.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
