# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: umihotaru.Nishiki-teki
PackageVersion: 3.99zhr
PackageLocale: en-US
Publisher: umihotaru
PackageName: Nishiki-teki
PackageUrl: https://umihotaru.work
License: Open Font License
ShortDescription: A font with very wide support for languages, even more so for Japanese.
Tags:
- font
- nishikiteki
- truetype
- kanaextendedb
- japanese
- latinalphabet
- greekalphabet
- taiwanesehokkienkana
- smallkanaextension
ManifestType: defaultLocale
ManifestVersion: 1.12.0