# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: umihotaru.Nishiki-teki
PackageVersion: 3.99zhr
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0