# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json
# Has not yet been submitted to pkgs due to: I've got cold feet about this manifest after I learned it wasn't lossless.

PackageIdentifier: OHZIInteractive.Compress
PackageVersion: 5.6.4
InstallerType: nullsoft
Installers:
- Architecture: x86
  InstallerUrl: https://s3.us-east-1.amazonaws.com/compress.mov/releases/CompressSetup.exe
  InstallerSha256: E4C0A97CED431B5FE277B707DB971F91CA074CEA90C745FA156D3743469E4087
ManifestType: installer
ManifestVersion: 1.28.0
