# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Kensington.DockWorks
PackageVersion: 1.4.10.0
PackageLocale: en-US
Publisher: Kensington Computer Products Group
PackageName: DockWorks
License: Proprietary
ShortDescription: g54h564rtwuj65rwj56y7rejk6r6jk
ManifestType: defaultLocale
ManifestVersion: 1.12.0
