# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json
PackageIdentifier: winitor.pestudio
PackageVersion: "9.61"
PackageLocale: en-US
Publisher: Marc Ochsenmeier
PackageName: Malware Initial Assessment
PackageUrl: https://www.winitor.com/download
License: Proprietary
ShortDescription: Accelerate your malware assessment workflow by quickly identifying key indicators in Windows executable files using our tool, pestudio.
Tags:
- malware-initial-assessment
ManifestType: defaultLocale
ManifestVersion: 1.28.0