# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: irzyxa.Volume2
PackageVersion: 1.1.9.470
InstallerType: zip
NestedInstallerType: exe
NestedInstallerFiles:
- RelativeFilePath: Setup_Volume2_1_1_9_x64.exe
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /silent
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/irzyxa/Volume2/releases/download/v1.1.9.470/Setup_Volume2_1_1_9_x64.zip
  InstallerSha256: 9733B12719A057F32D6540F39E5B939AC67DD1DB135D2BA1B69C9490992080CD
ManifestType: installer
ManifestVersion: 1.12.0