# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: HP.xRServices
PackageVersion: 25.0.16
PackageLocale: en-US
Publisher: HP Inc.
PackageName: HP xRServices PC
License: Proprietary
ShortDescription: The gateway to print industry’s first mixed reality-based service solution.
Moniker: xrservices
Tags:
- hp-xrservices-pc
- hpxrservicespc
- hp-xrservices-app
- hpxrservicesapp
ManifestType: defaultLocale
ManifestVersion: 1.12.0