# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: worproject.PEInstaller
PackageVersion: "1.1"
ReleaseDate: 2024-02-13
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: winpe\2\setup.exe
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: arm64
  InstallerUrl: https://github.com/worproject/dldserv-mirror/releases/download/13%2F02%2F2024/WoR-PE_Package_1.1.0.zip
  InstallerSha256: A039E28FE7E39147899B0634C15E336C3B26A6F76201092EBB9732474CD43D0A
ManifestType: installer
ManifestVersion: 1.12.0