# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: KeeperSecurity.PasswordImporterStandalone
PackageVersion: 17.0.3.0
PackageLocale: en-US
Publisher: Keeper Security, Inc.
PackageName: Password Importer Standalone
License: Proprietary
ShortDescription: Standalone version of the password importer tool used in Keeper Desktop.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
